// Base de datos de proveedores 
// Fuente: datos hardcodeados de ejemplo para prototipo

const PROVEEDORES = [
    {
        id: "ecoproveedores-uy",
        nombre: "EcoProveedores UY Ltda.",
        contacto: "Valentina Rocha",
        email: "v.rocha@ecoproveedores.com.uy",
        telefono: "+598 2 410 8800",
        certificaciones: ["ISO14001", "FSC", "EMAS"],
        mat_reciclados_pct: 80,
        embalaje_sostenible: "si",
        energia_renovable: "si",
        politica_devolucion: true,
        cobertura: "local",
        descripcion: "Empresa uruguaya especializada en papelería sustentable. Todos sus productos son fabricados con materiales de origen responsable y procesos certificados.",
        desafios: "Ampliar la red de proveedores de insumos reciclados a nivel local.",
        metas: "Alcanzar el 100% de embalaje biodegradable para 2026.",
        puntaje: 95,
        fecha_registro: "2025-03-10"
    },
    {
        id: "paperuy-sa",
        nombre: "PaperUY S.A.",
        contacto: "Rodrigo Bentancur",
        email: "rbentancur@paperuy.com.uy",
        telefono: "+598 2 900 1234",
        certificaciones: ["ISO14001", "FSC"],
        mat_reciclados_pct: 55,
        embalaje_sostenible: "parcial",
        energia_renovable: "no",
        politica_devolucion: true,
        cobertura: "local",
        descripcion: "Distribuidora nacional con más de 20 años en el mercado. Recientemente incorporó líneas de productos con certificación FSC.",
        desafios: "Migrar la logística a vehículos de menor emisión.",
        metas: "Incorporar energía solar en el depósito principal para 2025.",
        puntaje: 66,
        fecha_registro: "2025-04-02"
    },
    {
        id: "distribuidora-central",
        nombre: "Distribuidora Central S.R.L.",
        contacto: "Marcelo Suárez",
        email: "msuarez@distcentral.com.uy",
        telefono: "+598 2 308 5500",
        certificaciones: ["ISO14001"],
        mat_reciclados_pct: 40,
        embalaje_sostenible: "parcial",
        energia_renovable: "parcial",
        politica_devolucion: false,
        cobertura: "ambos",
        descripcion: "Proveedor de insumos de oficina con distribución nacional e internacional. Cuenta con certificación ISO 14001 vigente.",
        desafios: "Reducir packaging plástico en un 50% antes de fin de año.",
        metas: "Obtener certificación FSC para su línea de papel.",
        puntaje: 52,
        fecha_registro: "2025-04-18"
    },
    {
        id: "officeshop-uy",
        nombre: "OfficeShop Uruguay",
        contacto: "Lucía Fernández",
        email: "lfernandez@officeshop.com.uy",
        telefono: "+598 2 622 7700",
        certificaciones: [],
        mat_reciclados_pct: 20,
        embalaje_sostenible: "no",
        energia_renovable: "no",
        politica_devolucion: true,
        cobertura: "importado",
        descripcion: "Cadena de papelería con múltiples sucursales en Montevideo. Importa la mayoría de sus productos desde Brasil y Argentina.",
        desafios: "Incorporar criterios de sostenibilidad en la selección de proveedores internacionales.",
        metas: "Iniciar proceso de certificación ISO 14001 en 2026.",
        puntaje: 25,
        fecha_registro: "2025-05-01"
    },
    {
        id: "papeleria-del-sur",
        nombre: "Papelería del Sur",
        contacto: "Andrés Méndez",
        email: "andres@papeleriasur.uy",
        telefono: "+598 4 332 1900",
        certificaciones: ["FSC"],
        mat_reciclados_pct: 60,
        embalaje_sostenible: "si",
        energia_renovable: "parcial",
        politica_devolucion: false,
        cobertura: "local",
        descripcion: "Empresa familiar con base en Maldonado. Proveedora regional con fuerte compromiso con productos de papel de origen responsable.",
        desafios: "Formalizar procesos para obtener certificación ISO 14001.",
        metas: "Expandir cobertura a todo el territorio nacional manteniendo logística sostenible.",
        puntaje: 58,
        fecha_registro: "2025-05-15"
    }
];